#!/bin/sh

root="$PWD"
s="source/sc"
c="$root/source/c-precompiled"
export SC_LOAD_PATH="$root/$s"

compile_sc() {
  # create the c source code
  cd "$s" &&
  find -type f -name "*.sc" -exec sc --parents '{}' "$c" \; &&
  cd "$root" &&
  find "$c" -type f -exec ./exe/format-c -i '{}' \;
  mv "$c/main/spline-path-h.c" "$c/main/spline-path.h"
}

mkdir -p "$c" &&
compile_sc
