#!/bin/sh -e
# the shared library must have already been compiled,
# the compiled one from the temp directory is used

export MALLOC_CHECK_=3
export LD_LIBRARY_PATH="$PWD/temp"
./temp/test-spline-path
exit
./temp/test-queue
./temp/test-arrayn
./temp/test-mi-list
./temp/test-quicksort
./temp/test-random
./temp/test-set
./temp/test-hashtable
./temp/test-thread-pool
#./temp/test-ikv
